### ISSUE TITLE
Weird annotation

### ISSUE THREAD

**Issue by virdiignis** [providedh/ACDH_Salzburg_recipes#7]
Hi,
in recipe_6869.xml i found intteresting case of annotation.
In ingredient list there is:
`<object type="ingredient" xml:id="pastetenteig">Pastetenteig</object>`

and in text I stumbled upon a followng fragment:
`<objectName ref="#pastete">Pasteten</objectName> darzu auff von weissem <objectName ref="#teig">Teig</objectName>`

not #pastete nor #teig are present on it's own in ingredients list.

Regards,
Greg

**Comment by rsouza** [comment]
Hi Greg.
Yes, it is curious, but it seems to be because in German some words are concatenated. 

Pastetenteig = pastry dough
Pasten = pastry
Teig = dough

The original recipe mentioned the two words separated, but it seems the annotator for the wordpress database decided to list it as a single ingredient. See:

`<content:encoded>Nim(m) ein Karpffen / vnd schupe jn / thu jn auff / vnd mach stücker darauß / treib ein Pasteten darzu auff von weissem Teig / leg die Karpffenstück darein / sträw Pfeffer / Ingwer vnnd Saltz / darüber / thu Butter / die vngeschmältzt ist / vnd ein wenig schwartze Rosein / die sauber außgewäschen seyn / auch gesaltzene Limonien / die fein breit geschnitten / darein / mach die Pasteten zu / vnd laß backen / schneidt sie auff / vnnd geuß ein Karpffenschweiß / der gesotten vnd angemacht ist / darüber / scheubs wider in Ofen / vnnd laß auffsieden / gibs warm auff ein Tisch / so ist es gut vnd wolgeschmack.</content:encoded>`

And the list was:

```
<category domain="Zutaten" nicename="butter">Butter</category>
<category domain="Zutaten" nicename="ingwer">Ingwer</category>
<category domain="Zutaten" nicename="karpfen">Karpfen</category>
<category domain="Zutaten" nicename="karpfenschweiss">Karpfenschweiß</category>
<category domain="Zutaten" nicename="limonen-gesalzen">Limonen (gesalzen)</category>
<category domain="MaterielleKultur" nicename="ofen">Ofen</category>
<category domain="Zutaten" nicename="pastetenteig">Pastetenteig</category>
<category domain="Zutaten" nicename="pfeffer">Pfeffer</category>
<category domain="Zutaten" nicename="rosinen-schwarz">Rosinen (schwarz)</category>
<category domain="Zutaten" nicename="salz">Salz</category>
<category domain="Zutaten" nicename="sauce-schwarz">Sauce (schwarz)</category>
```

All the best.
Renato

**Comment by virdiignis** [comment]
Well that still leaves us with references to unexistant objects. Not a big issue if we won't use files with this error, but I wanted to note it here.

**Comment by rsouza** [comment]
Thanks. 
For the German speakers, it seems very natural to have constructions like this, so we may have to deal with this case in other recipes. I don't know if this is a case we should avoid or purposely include!
